//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.DetailBills = new HashSet<DetailBill>();
        }
    
        public int idBill { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idShipper { get; set; }
        public Nullable<decimal> totalMoney { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<decimal> promotionCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<DetailBill> DetailBills { get; set; }
    }
}
