//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyProduct
    {
        public BuyProduct()
        {
            this.DetailBuys = new HashSet<DetailBuy>();
        }
    
        public int idBuy { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> maybeRecDate { get; set; }
        public Nullable<System.DateTime> receiveDate { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<DetailBuy> DetailBuys { get; set; }
    }
}
