//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public Control()
        {
            this.ControlRoles = new HashSet<ControlRole>();
        }
    
        public int idControl { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<ControlRole> ControlRoles { get; set; }
    }
}
