//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int idCustomer { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string gender { get; set; }
        public string idPersoner { get; set; }
        public Nullable<decimal> promotion { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public string image { get; set; }
        public string address { get; set; }
        public Nullable<int> coin { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
