//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Bills = new HashSet<Bill>();
            this.DailySystems = new HashSet<DailySystem>();
            this.Salaries = new HashSet<Salary>();
        }
    
        public int idEmployee { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<int> gender { get; set; }
        public string idPersoner { get; set; }
        public string image { get; set; }
        public Nullable<int> status { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> idRole { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<DailySystem> DailySystems { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
