//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DetailBills = new HashSet<DetailBill>();
            this.DetailBuys = new HashSet<DetailBuy>();
        }
    
        public int idProduct { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string moreImage { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> promotionPrice { get; set; }
        public string detail { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<int> wanranty { get; set; }
        public Nullable<int> idSupplier { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DetailBill> DetailBills { get; set; }
        public virtual ICollection<DetailBuy> DetailBuys { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
