//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.ControlRoles = new HashSet<ControlRole>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int idRole { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual ICollection<ControlRole> ControlRoles { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
