//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.BuyProducts = new HashSet<BuyProduct>();
            this.Products = new HashSet<Product>();
        }
    
        public int idSupplier { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public string phone { get; set; }
        public string codeTax { get; set; }
    
        public virtual ICollection<BuyProduct> BuyProducts { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
